### ISSUE TITLE
Is there a way that I can obtain the electrical losses in a network using PyPSA? 

### ISSUE THREAD

**Issue by kellydosocorro** [PyPSA/PyPSA#106]
Sorry if my question is too obvious, but I really can't understand it at all. What I need is the electrical losses resulted of Σ (R * I²). Is there a way to obtain or perhaps I just have to implement this? Since, thanks for this framework, it helps me a lot.

**Comment by fneum** [comment]
Thanks for your question. The answer depends on whether you are referring to (1) linear optimal power flow (`network.lopf`) or (2) NR power flow (`network.pf`).

1. The assumptions for the linearised DC power flow equations governing line flows in `network.lopf` lead to a lossless network model.

2. For NR power flow, have a look at the sign conventions where there is a hint how to calculate active power losses. 

> If p0 > 0 and p1 < 0 for a branch then active power flows from bus0 to bus1; p0+p1 > 0 is the active power losses for this direction of power flow. -- https://pypsa.readthedocs.io/en/latest/design.html#sign-conventions

PS: For this kind of questions we usually prefer the PyPSA mailing list (https://groups.google.com/group/pypsa) since there are more people reading the list than issues. We use issues for feature requests and bugs. Just a hint for next time.

**Comment by fneum** [comment]
Please close if this helped you.

**Comment by kellydosocorro** [comment]
Yes, it helped me, thank you!
