### ISSUE TITLE
Use __slots__ in network class

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#221]
Derived from #206 but issue to discuss

We could use ``__slots__`` in the network class which can reduce the RAM usage significantly, see [here](https://book.pythontips.com/en/latest/__slots__magic.html). This could look like this

```python
slots = [c['list_name'] for c in n.components.values()]
slots.remove('networks')
slots += [s + '_t' for s in slots] (+ possible other stuff like srid) 
__slots__ = slots 
right at the beginning of the network class definition. But it requires that __slots__ can be modified when overwriting components, which I am not sure of.
```
right in the beginning of the class definition. 

**Downside**: arbitrary objects which are not in the ``__slots__`` cannot be added to the network object (`n.long_name = 'very_long_name'` would not work)

**Comment by fneum** [comment]
Possible workaround for attaching arbitrary objects to a network: add `n.meta` which is initialised as an empty dictionary where such objects can be labelled and stored.

**Comment by coroa** [comment]
`__slots__` as your link describes avoids the instantiation of one dictionary for each instance of the class you attach it to. Ie. if you have a small class with only a couple of known attributes (say, two integers and a string) of which you want to have millions of instances; then it makes sense to use slots since then you don't store millions of dictionaries, integers and strings, but only the integers and strings. That's why the var data instance in pyomo uses it (and rightly so). Network as a class only has a few instances at best during a typical run. If we still had individual components (where each bus is represented with an object, then yes), but here it will not benefit you.

**Comment by FabianHofmann** [comment]
good point! thanks, I'll close this one
