### ISSUE TITLE
Do we need the pypsa.geo module?

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#230]
The `pypsa.geo` module currently has three functions: `haversine_pts`, `haversine` and `area_from_lon_lat_poly`.

The latter is used nowhere and `pyproj` is not even in `pypsa`'s dependencies. I think this can definitely go.

The haversine functions are only used in networkclustering. One could move them there.

Any opinions?

**Comment by FabianHofmann** [comment]
Yes, let's remove the `area_from_lon_lat_poly` (perhaps with a deprecated warning first?)

Generally, having a geo module is not too bad. I could image that some functions especially those of the voronoi cell calculation could be moved from vresutils into pypsa. There might be more usecases. 

But how about removing the `stats` module? It was only introduced due to counter-testing the linopf module.

**Comment by fneum** [comment]
Sounds good! Maybe we could reuse some of the functions from stats for unit tests?
