### ISSUE TITLE
AttributeError: type object 'ConfigBlock' has no attribute '_all_slots'

### ISSUE THREAD

**Issue by amirhoseinsh** [PyPSA/PyPSA#34]
hi, I imported ` pypsa`, and installed it first with `pip` and it get me this error, after that I installed manually and again this error appear! I really need help, thanks
Error: 

  File "/usr/local/lib/python2.7/dist-packages/pyomo/pysp/util/config.py", line 151, in __setattr__
    if name in ConfigBlock._all_slots: AttributeError: type object 'ConfigBlock' has no attribute '_all_slots'

**Comment by coroa** [comment]
hi,

Most of the problems reported here are due to a broken installation of pyomo. And yours looks like that, too.

Please check that you are able to complete a minimal pyomo optimisation problem with your python installation first:
```python
import pyomo.environ as pe
m = pe.ConcreteModel()
m.x = pe.Var()
m.c = pe.Constraint(expr=m.x >= 1)
m.obj = pe.Objective(expr=m.x)
opt = pe.SolverFactory('glpk')
results = opt.solve(m)
assert results['Solver'][0]['Termination condition'].key == 'optimal'
assert pe.value(m.x) == 1
```

If you get an error there, fix your installation according to the [pyomo documentation](http://www.pyomo.org/documentation/) or look there for help.

Only if that is not the case, reopen this issue here. Make sure to include a complete stack trace, i.e. the full error report for a minimal example!

Closing, since it's most likely a pyomo only issue!
