### ISSUE TITLE
Multi-Horizon Investment

### ISSUE THREAD

**Issue by nworbmot** [PyPSA/PyPSA#36]
As of Version 13.1, PyPSA only considers investment in one horizon, e.g. for a single year. We'd like to implement investment over multiple horizons simultaneously, e.g. for 2020, 2025, 2030, 2035, etc., to optimise investments dynamically over several years e.g. under tightening CO2 constraints. The objective function then becomes the discounted net present value (NPV) of energy system costs. Other open models such as [OSeMOSYS](http://www.osemosys.org/), [Genesys](http://www.genesys.rwth-aachen.de/), [DIETER](http://www.diw.de/dieter) (I think) and [SWITCH](https://github.com/switch-model/switch) do this already; we can copy their implementations and avoid reinventing the wheel.

On the data side:

i) We need a second index for snapshots that gives the investment year, e.g.
snapshots = [(2020, "windy day"), (2020, "sunny day"), (2030, "windy day"), (2030, "sunny day")]
The representative weather for each investment year may change with the year (e.g. due to climate change); the number of representative snapshots for each investment year may also change.

ii) We need different CO2/renewable constraints for different investment years.

iii) For assets, we need to take account of build years and lifetimes for generation, storage and transmission assets, e.g. we need additional fields

name, build year, life time, cost
wind-in-2020, 2020, 20, 1200
wind-in-2025, 2025, 20, 1000
wind-in-2030, 2030, 25, 900

Then in the code we need to activate assets in the constraints depending on whether they are around in the investment year or not.
We also need to take account of the discount rate as a pre-factor to get the NPV for each investment year.
Perhaps this should be linked to issue #37 of separating the snapshot_weighting from the duration of each snapshot, which was discussed on the PyPSA mailing list before.
BEWARE 1): The final investment horizon has to be treated carefully, to avoid end-of-horizon effects whereby assets are only built for the final horizon and have no value for the rest of their lifetimes. Either model 20 years further (with lower intra-year resolution) or have a "salvage value" for investments made in the final investment horizon (I think OSeMOSYS had this).
BEWARE 2): p_nom_max may become linked between different generators as potentials are used up.

**Comment by arjunane** [comment]
Hi @nworbmot ,
just some short thoughts concerning you suggestions:
i) The number and the lengths of representative snapshots may vary as well.
ii) It would be usefull to be able to implement a CO2 constrain over the whole timeperiod. This would reflect a budget approach, where a specific investment year would not be constraint, but the overall sum. But by doing this, you would have to think about taking those years into concideration, which may not be targeted. E.g. 2021, 2022, 2023 and 2024 if you only look at 2020 an 2025.  

As a short remark, to my knowledge and according to the model documentation, there is no Multi-Horizon-Investment  at DIETER.

Really looking forward in using this feature within pypsa.

**Comment by miek770** [comment]
This is great, I logged in to see if there was already an issue open for this subject. Optimization over long time periods cannot be used easily for real projects if this isn't builtin. I currently optimize over 1 year and perform the economic calculations separately, but it would be even better if the LOPF took it all into account.

Ideally, I would like to be able to:

1. Optimize on either the equivalent annual cost (EAC) or the NPV;
2. Input escalation as a percentage instead of putting it manually in the time series (i.e.: margine_cost);
3. Input discount rate as a percentage, as @nworbmot mentioned;
4. Consider the residual value of the asset at the end of the cycle (the salvage value @nworbmot mentioned).

Were there further discussions regarding this since this issue was open? I would like to help if I can; this is something I'll need sooner than later for real projects.

**Comment by nworbmot** [comment]
We're considering doing this soonish (i.e. next few months) since many people have been requesting this. Some of your numbered points are things we prefer to leave to the users, to give the underlying code as much flexibility as possible.

What we'll probably do is start a new branch and develop the code over a few weeks. It would be super helpful at that point if you could test the code for correct functioning and design.

**Comment by miek770** [comment]
Great thanks, I'll follow the development and test when possible.

Could you please indicate which features you're planning on including or leaving out? Or would you rather confirm at a later date?

Happy New year!

**Comment by nworbmot** [comment]
The code behind this paper https://doi.org/10.1038/s41560-018-0159-3, which does multi-horizon investment with perfect foresight, is also openly online and can be mined for tips.

**Comment by Marissa01** [comment]
Hello! Just was wondering what the current status of this issue request is? Is there an expected timeframe as to when this will be incorporated into PyPSA?  I really enjoy using PyPSA and think this would be an extremely useful and great addition!

**Comment by nworbmot** [comment]
Hi all, we have sketched the math and code design for the multi-horizon investment optimization, as a prelude to programming it:
https://nworbmot.org/energy/multihorizon.pdf
This includes a review of how other model frameworks handle it, and how we think it best to include it in PyPSA. We've tried to think of all use cases, but please chime in with opinions or suggestions!
In a few weeks we'll start the programming.

**Comment by clameron** [comment]
Hi Tom, thanks for all your work. It's good to see you and the team addressing this feature.

One aspect that I think deserves careful consideration is how you plan on addressing inter-period constraints, e.g. battery state-of-charge and generator ramp rates. Insofar as temporal representation in these multi-year models, the community seems to be moving away from seasonal time slices to representative periods, e.g. days (see: Poncelet, Pfenninger, Nahmmacher, etc..). Although modelling intra-period constraints is trivial, representing inter-period constraints is not.

Leander Kotzur and colleagues have a nice paper [here](https://www.sciencedirect.com/science/article/pii/S0306261918300242?casa_token=lK8MDlcXUzYAAAAA:V6w4pzBqAclzWSp4US7CMOvj1D48_tmdxTeZaPrFZwtf7UYsC5U_U-fk5nH46FTbJzV0i4gTtg) outlining a method/equations that account for inter-period dynamics within the representative period setting. 

Pfenninger and the other developers of Calliope have included these equations into the most recent version of Calliope, albeit for a single year model. 

It would be great to see this feature available in PyPSA. I'm always happy to chat about this, and temporal aggregation methods in general. 

Cheers!
Cam

**Comment by nworbmot** [comment]
Thanks Cam! At the moment we've mostly stuck to including the full year at hourly resolution, since any aggregation can miss important effects and extreme events (e.g. long periods with high space heating demand and low wind and solar generation). The seasonal slices in the PDF were just as an example.
We're aware of that paper by @l-kotzur and I'm a big fan of the method to mix daily and seasonal resolutions. I'd see including it as something orthogonal to the multi-horizon equations (but computationally necessary for large networks), that we can address separately.

**Comment by nworbmot** [comment]
The calliope implementation of the time series aggregation is described [here in their documentation](https://github.com/calliope-project/calliope/blob/master/doc/user/advanced_features.rst).

**Comment by clameron** [comment]
Awesome, thanks, Tom. I agree that aggregation brings with it a whole slew
of undesirable effects. But, like you said, it's perhaps necessary for
large networks and many investment periods.

I just thought I'd bring it up early on because implementing Leander's
equations is distinct from typical multi-horizon equations in that you have
an additional state space; which I think of as a map F from D -> R where D
is the set of days in the year in question and R is the set of (weighted)
representative days selected to represent that same year. The dynamics of
technologies w/ inter-period coupling, e.g. storage, are then partly
described by this mapping. For instance, the storage charging profiles are
the same for all {d \in D | F(d) = some fixed r \in R}  So, as far as the
coding goes, it adds a level of complexity.

Anyways, having followed your project it's clear this is something you're
both aware and capable of implementing.  It's just of particular interest
of mine as I'm currently writing a paper on a hybrid
optimization/clustering method to select representative days for capacity
expansion models as part of my PhD work.

In any case, thanks for you and your team's hard work.

Best,
Cam

**Comment by nworbmot** [comment]
Just a note that @l-kotzur's clustering-with-seasonal-storage method has been implement by @ClaraBuettner for PyPSA in the eTraGo project as extra functionality:

https://github.com/openego/eTraGo/blob/81e004a4e1cfa85ee91863d8425ad8d18bae21df/etrago/tools/constraints.py#L1000

We'd like to integrate this into PyPSA soon.

**Comment by fneum** [comment]
Fantastic! Is there a PR in preparation? This is for `pyomo`. Would be nice to also have a `nomopyomo` variant, but one step at a time.

**Comment by l-kotzur** [comment]
@nworbmot Cool! If there are any questions, do not hesitate to contact us.

I also want to point out that @maximilian-hoffmann has some novel clustering methodologies prepared, which we will publish with [tsam](https://github.com/FZJ-IEK3-VSA/tsam) hopefully soon.

**Comment by fneum** [comment]
Ah, nice. Looking forward. I played around with the segmentation in `tsam` a couple of weeks back: https://github.com/PyPSA/pypsa-eur/pull/186

**Comment by ClaraBuettner** [comment]
> Fantastic! Is there a PR in preparation? This is for `pyomo`. Would be nice to also have a `nomopyomo` variant, but one step at a time.

I implemented the seasonal storage functionality in our tool eTraGo which is based on PyPSA. I think we can migrate the function to PyPSA, but I can't create a PR directly. 
Have you already implemented the snapshot clustering and only need the extra functionalities for seasonal storage or do you need both? (the clustering method is implemented in eTraGo separately: https://github.com/openego/eTraGo/blob/dev/etrago/cluster/snapshot.py)

Unfortunately we use this function only rarely because there are still quite large deviations to the original problem and the solving time rises significantly when adding the constraints for seasonal storage. We are planning to work on this but I haven't had time for this up to now.

**Comment by l-kotzur** [comment]
@ClaraBuettner Concerning solving time, have you implemented the simplification described in Appendix B: https://arxiv.org/pdf/1710.07593.pdf

**Comment by ClaraBuettner** [comment]
No, I have not implemented the simplification yet. But I will take a look at this, thank you for the hint.

**Comment by nworbmot** [comment]
This issue is addressed in PR https://github.com/PyPSA/PyPSA/pull/211. The code is working, but @lisazeyen is finessing the interface.

**Comment by FabianHofmann** [comment]
close by #270
