### ISSUE TITLE
network.lopf() with remote solver (ssh)

### ISSUE THREAD

**Issue by neunzehnachtneun** [PyPSA/PyPSA#45]
Hi together,
this is rather a question than an issue, but I want to tell you.
We are using PyPSA to build a model and use network.lopf to solve it. To get this done, there seem to be two possibilities for us. We are building the models locally on our machines. To solve the model we can use open source solvers like glpk also locally, which works great but is to slow to solve the whole model. So this is only an option for test cases. The alternative is to build the model locally and solve it using our remote server and our commercial solver. The server is accessible via ssh.
As this is a real challenge to us, I would like to ask, if you have any idea, how to run PyPSA with a custom remote access solver.

Thanks in advance!

**Comment by coroa** [comment]
Hi Sebastian,

Remote solver per-se would be rather a pyomo support question (The
python modelling layer behind pypsa, which lives at
https://github.com/Pyomo/pyomo). As far as I know, they do not support
anything like this.

There are two distinct approaches I'd recommend you:

1. Gurobi as well as CPLEX (and probably also other solvers) are by
default invoked by dumping the optimization problem into a temporary
lp-file and then calling an executable (f.ex. gurobi.sh for gurobi) with
the solver options as command line arguments and the path to the
lp-file.

You can choose where to store the lp-file and the solutions by something
like:

from pyutilib.services import TempfileManager
TempfileManager.tempdir = '/some/path/randompath'

And you can influence which solver executable is called by passing an
extra argument to pyomos SolverFactory (the call in
pypsa.opf.network_lopf_prepare_solver)

import pyomo.environ as po
opt = po.SolverFactory("gurobi", executable="remote_gurobi.sh")

You would then have to write remote_gurobi.sh in a way to transfer the
lp-file to the remote host, call gurobi.sh there using ssh and forward
the stdout and stderr locally and finally copy the written solution
files back to /some/path/randompath.

Perhaps you can get around the transferring there and back by pointing
TempfileManager.tempdir to a mount point (refer to sshfs).

That's pretty much what you had in mind, isn't it?

Drawback is: Pyomo takes quite a lot of time and memory in the lp
writing phase (actually often more memory than gurobi itself). And the
lp-files are often a lot bigger than the actual export.

2. I think it would be easier and smarter to export the pypsa model to a
netcdf file (network.export_to_netcdf), sent that file over to the
remote host, call a small solve_network python script using ssh that
reads that file calls lopf on it and in case of success re-exports the
result, transfers it back and re-imports it. Otherwise it raises a
RemoteException including the remote stack trace.

The hard bit here would be designing a nice ideally non-blocking
interface, so one can continue interacting with and looking at the
network, while the optimal power flow is in progress.

We would definitely be interested in the second option. It sounds like a
very valuable addition!

Best,
Jonas

**Comment by neunzehnachtneun** [comment]
Thank you @coroa !

First of all yes, you're right. This is rather a question regarding Pyomo than PyPSA. An I have already asked them. So just for information, if someone else with a similar problem is looking for a solution. There is a pyomo plugin called NEOS, which is a server and maybe can adapted to a custom remote accessible solver. At the moment I am still working on that.

Both of your approaches are rather workarounds, but your inputs are useful definitely.
I just want to add a drawback af your second idea. In our IT-architecture there are user laptops where it is allowed to work with python environments like conda. Our server is a Windows machine, where a commercial solver is installed but neither conda nor other needed libraries (like PyPSA etc.). So there is this second barrier to get our python environment working there.

But nevertheless I think at the moment your suggestion fits better to our workflow than to build a workaround solution consisting of the packages PyPSA, Pyomo, Pyro4 and Paramiko just to get access to our ssh server. Your approach is much cleaner and more pragmatic.

I will give feedback again, when we solved the issue.

Best,
Sebastian

**Comment by coroa** [comment]
Just for reference: The issue in pyomo is https://github.com/Pyomo/pyomo/issues/726.
