### ISSUE TITLE
Transformer nominal ratings not respected in network.pf()

### ISSUE THREAD

**Issue by dgusain1** [PyPSA/PyPSA#53]
Hi
I have a CIGRE MV network. The transformer is rated at 25MVA, but I can conviniently send much, much higher powers (~70MW) through it by increasing loads. Technically, the load flow should not converge. Running the same network powerflow in pandapower results in LoadFlowNotConvergedError, which seems reasonable.

I assume this is because transformer s_nom isn't factored in when performing load flow? The load flow fails when lines are under-rated. Doesnt seem to be the case with transformer ratings.

**Comment by nworbmot** [comment]
The load flow does not take into account the s_nom of lines or transformers, except for the per unit calculation of impedance. This should be the same in pandapower - the failure is because there are either voltage problems or numerical instability. Please make sure the impedances are correctly specified.
