### ISSUE TITLE
Plotting with cartopy requires cartopy>=0.16

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#59]
Using PyPSA's plotting functionality with cartopy requires a cartopy version higher than 0.16, since the `with_scale(...)` function on a `NaturalEarthFeature` was introduced only then.
https://scitools.org.uk/cartopy/docs/latest/whats_new.html#what-s-new-in-cartopy-0-16

The function is used in `draw_map(...)`
https://github.com/PyPSA/PyPSA/blob/46954b1b3c21460550f7104681517065279a53b7/pypsa/plot.py#L335-L345

Would it be an option to assert the version while trying to import?
https://github.com/PyPSA/PyPSA/blob/46954b1b3c21460550f7104681517065279a53b7/pypsa/plot.py#L54-L61

It should probably not end up in the `requirements.yaml`.

**Comment by coroa** [comment]
We can either require a minimum version of 0.16 in environment.yaml and
setup.py, which is my favorite.

Or, since all the with_scale option does is to select a higher resolution, which
is optional, change the offending line to

border = cartopy.feature.BORDERS
if version.parse(cartopy.__version__) >= version.parse("0.16"):
    border = border.with_scale(resolution)


with a "from packaging import version" on top, since packaging is a
dependency of "setuptools", we already pull that package in.

feel free to prepare a PR with one of the two fixes. Either is fine.

Best,
Jonas

**Comment by coroa** [comment]
Automatic closing does not seem to work with `[Closes #59]`, use `(closes #59)` next time.
