### ISSUE TITLE
What is glpk or how to solve the minimal-example-lopf can not outpu

### ISSUE THREAD

**Issue by Yunanshu** [PyPSA/PyPSA#63]
I am green hand, when i run the example minimal-example-lopf,there is a question:
File "D:\Anaconda3\lib\site-packages\pyomo\opt\solver\shellcmd.py", line 126, in available
    raise ApplicationError(msg % self.name)

ApplicationError: No executable found for solver 'glpk' 
I hope you can help me!
Thanks!

**Comment by fneum** [comment]
In order to use PyPSA, you need a solver that finds an optimal solution to e.g. the linear optimal power flow (LOPF) problem. PyPSA passes optimisation problems to an external solver. There are the free solvers `GLPK` and `Cbc` or commercial solvers like `Gurobi`.

If you follow the installation steps for PyPSA (https://pypsa.org/doc/installation.html) you should be able to set up a running environment.

Also, please consider using the forum/mailing list (https://pypsa.org/doc/mailing_list.html) to post questions.

**Comment by coroa** [comment]
As @fneum pointed out above please address questions of usage to the mailing list, where more people can actively support!
