### ISSUE TITLE
Operating Reserves Co-Optimization

### ISSUE THREAD

**Issue by ToeKneeShoe** [PyPSA/PyPSA#74]
Hi, I was wondering if this is currently possible.

Example with 2 generators

Objective: `min{ MC_p1*P_1  + MC_p2*P_2 + MC_r2*R_1 + MC_r2*R_2 }`
with MC = Marginal Cost

Constraints:
`P_1 + P_2 = Demand `
`R_1 + R_2 >= Min_System_Reserve `

`0<= P_1 + R_1 <= Max_nom_P_1`
`0<= P_2 + R_2 <= Max_nom_P_2`
`0<= R_1 <= Max_nom_R1`
`0<= R_2 <= Max_nom_R2`

With default of max_nom_reserve as 0.

I couldn't find anything in the documentation about reserves.

**Comment by fneum** [comment]
To cover this, you would have to add extra constraints to the model with your own code.
Have a look at the keyword `extra_functionality` in the function `Network.lopf()`.
https://github.com/PyPSA/PyPSA/blob/c28cbb8f46937d5386024e499644d8a23667fcac/pypsa/opf.py#L1526-L1531
It might be a bit tricky, since you do not only want to add additional constraints but also change e.g. the nodal balance. 

For an example, how the `extra_functionality` keyword is used, see:
https://github.com/PyPSA/PyPSA/blob/master/examples/sector-coupling/replace-generator-storage-units-with-store.py

Also, please consider using the forum/mailing list (https://pypsa.org/doc/mailing_list.html) to post questions, where more people can actively support.
