### ISSUE TITLE
Storage units state of charge is calculated with objective weightings instead of store weightings

### ISSUE THREAD

**Issue by sophie-pelland** [PyPSA/PyPSA#796]
## Checklist

- I am using version 0.25.2 of PyPSA

## Describe the Bug

We are doing power system optimization over multiple years at an hourly time step, using representative days. Objective weightings vary with the day (0 for days other than representative days), and store and generator weightings are set to 1 during the representative days
[storage_units-state_of_charge_bug_example.xlsx](https://github.com/PyPSA/PyPSA/files/13592409/storage_units-state_of_charge_bug_example.xlsx)
.

We run network.optimize.solve_model to do the optimization. In the model outputs, the storage unit states of charge correspond to what you would get if you used the objective weightings, not the store weightings. I have included an Excel spreadsheet showing the model outputs for one storage unit, my calculation of the state of charge using the objective weightings, which matches the states of charge in the outputs.

## Error Message

No error message

**Comment by fneum** [comment]
Could you share a small network so that we can reproduce the error? I am a bit puzzled because I checked, and the snapshot weightings for stores should be used for the elapsed hours:

https://github.com/PyPSA/PyPSA/blob/master/pypsa/optimization/constraints.py#L741

Just to confirm, you are using `n.optimize()` not `n.lopf()`?

**Comment by sophie-pelland** [comment]
@fneum Finally, the bug was on our end! Apologies for this. I will close the issue.
