### ISSUE TITLE
Collections Anaconda installation issue

### ISSUE THREAD

**Issue by Misbahrani** [PyPSA/PyPSA#83]
Hello
I am unable to install collection package for anaconda, screenshot attached.
![image](https://user-images.githubusercontent.com/52325843/61620821-0c66b500-ac8b-11e9-8684-868d1baaf6f2.png)
I have also searched on the anaconda.org, but there is sortedcollection available ,which I have downloaded, but it doesn't work with namedtuple

**Comment by coroa** [comment]
I fail to understand how this relates to PyPSA. You can check the requirements of PyPSA in the its conda-forge [recipe](https://github.com/conda-forge/pypsa-feedstock/blob/6a1ee0201030e58cc76f8b95c557bd1e90246ea4/recipe/meta.yaml#L23-L33).

It is possible you mean the package `collections`, which also contains the module for `namedtuple`s. This package has already been part of python's standard library since python 2.4 and, hence, does not need to be installed separately.

Can you please describe what you are intending to do and why?

**Comment by Misbahrani** [comment]
I am sorry, I posted this issue in the pyPSA section on the github, actually I had opened multiple tabs on pyPSA, pandapower & following 
https://github.com/GridMod/RTS-GMLC/tree/master/RTS_Data/FormattedData
I was wondering that, i didnt get any response on this issue, as usually community members reply within a day. I was trying to run topysp.py file when i got error with namedtuple as shown in the following screen shot
![image](https://user-images.githubusercontent.com/52325843/61767636-58863680-adfe-11e9-8111-8c7fec82df6a.png)
I have removed verbose and now its working
![image](https://user-images.githubusercontent.com/52325843/61767713-94210080-adfe-11e9-9aaf-5674509b1d88.png)
Thanks for your response.

**Comment by coroa** [comment]
Glad, it's working now.
