### ISSUE TITLE
Cannot download or load min example notebook via binder

### ISSUE THREAD

**Issue by fhg-isi** [PyPSA/PyPSA#934]
https://pypsa.readthedocs.io/en/latest/examples/minimal_example_pf.html
https://mybinder.org/v2/gh/PyPSA/pypsa/vmaster?labpath=examples/notebooks/minimal_example_pf.ipynb

![image](https://github.com/PyPSA/PyPSA/assets/76424482/09fe7bae-bcec-4263-99ad-45c64ee4dcdf)

![image](https://github.com/PyPSA/PyPSA/assets/76424482/b143897e-d7e4-4ec9-8841-f2e84ff59570)

When you fix the min example, you might also want to explain, why three "nodes" are required for min example and a single "bus" is not sufficient.

**Comment by lkstrp** [comment]
Thanks for raising this @fhg-isi ! Should be fixed with the PR.
Buses are the fundamental nodes, see [here](https://pypsa.readthedocs.io/en/latest/design.html#buses-are-the-fundamental-nodes). You could also create a single bus network, see a more complicated [example](https://pypsa.readthedocs.io/en/latest/examples/capacity-expansion-planning-single-node.html#) with a single node. 
So this is just a minimal, not the most minimal example.
